version: '2'
services:
  db:
    image: mysql:5.7
    command: "--innodb_use_native_aio=0"
    environment:
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/volumes:/var/lib/mysql
    user: "1000:50"
      
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      USER: "root"
      PASSWORD: "password"
    tty: true
    stdin_open: true